/// @file oci_signing_unit_test.cpp
/// @brief OCI Request Signing Version 1 — canonical form and header shape
///        (`.kiro/specs/oci-cloud-provider/`, Requirements 1.4-1.6).
///
/// **The load-bearing assertions verify the signature against a canonical
/// string built independently, by hand, in this file** — not against a stored
/// signature blob, and not by calling the signer twice. A golden signature
/// would pin whatever the implementation happens to produce, including a wrong
/// header order, and would have to be regenerated by the very code under test
/// the moment anything changed. Verifying with OpenSSL against a string spelled
/// out here asks the question that actually matters: *are these the bytes OCI
/// will hash on its side?*
///
/// That framing is the point, because of how this scheme fails. The signature
/// covers an **ordered** string. Get the order wrong and every request is still
/// perfectly well-formed — correct headers, correct JSON, valid base64 — and
/// the service answers 401 with nothing indicating which of the two sides
/// disagrees. `design.md`'s first draft did get it wrong, putting
/// `(request-target)` before `date`; the Task 0 spike corrected it against
/// `oracle/oci-go-sdk`'s `common/http_signer.go`. The negative control below
/// pins that correction: it asserts the draft's order does **not** verify, so
/// these cases cannot silently start passing for a signer that reintroduces it.
///
/// No network, no OCI account: signing is a pure function of the config, the
/// request line and the clock, and the clock is injected.

#define BOOST_TEST_MODULE oci_signing_unit_test
#include <boost/test/unit_test.hpp>

#include <raft/oci_signing.hpp>

#include <openssl/evp.h>
#include <openssl/pem.h>

#include <ctime>
#include <map>
#include <memory>
#include <string>
#include <vector>

namespace {

using kythira::oci_client_config;
namespace signing = kythira::oci_signing;

/// A pinned instant so `date` — and therefore the whole signature — is
/// deterministic. 1786363200 == Mon, 10 Aug 2026 12:00:00 GMT; cross-checked
/// against `date -u -d @1786363200` rather than computed by the code the header
/// under test shares.
constexpr std::time_t fixed_time = 1786363200;
constexpr const char* fixed_date = "Mon, 10 Aug 2026 12:00:00 GMT";

constexpr const char* test_host = "iaas.us-phoenix-1.oraclecloud.com";
constexpr const char* test_target = "/20160918/instancePools/ocid1.instancepool.oc1..cccc";

/// Generated per run rather than checked in: nothing here depends on *which*
/// key is used, only that the signature verifies under its public half, and a
/// private key in the tree is a thing someone eventually copies somewhere real.
auto generate_rsa_key_pem() -> std::string {
    EVP_PKEY* raw = nullptr;
    EVP_PKEY_CTX* ctx = EVP_PKEY_CTX_new_id(EVP_PKEY_RSA, nullptr);
    BOOST_REQUIRE(ctx != nullptr);
    BOOST_REQUIRE(EVP_PKEY_keygen_init(ctx) == 1);
    BOOST_REQUIRE(EVP_PKEY_CTX_set_rsa_keygen_bits(ctx, 2048) > 0);
    BOOST_REQUIRE(EVP_PKEY_keygen(ctx, &raw) == 1);
    EVP_PKEY_CTX_free(ctx);

    BIO* bio = BIO_new(BIO_s_mem());
    PEM_write_bio_PrivateKey(bio, raw, nullptr, nullptr, 0, nullptr, nullptr);
    char* data = nullptr;
    const long len = BIO_get_mem_data(bio, &data);  // NOLINT(google-runtime-int) — OpenSSL's type
    std::string pem(data, static_cast<std::size_t>(len));
    BIO_free_all(bio);
    EVP_PKEY_free(raw);
    return pem;
}

auto make_config(const std::string& pem) -> oci_client_config {
    oci_client_config cfg;
    cfg.region = "us-phoenix-1";
    cfg.tenancy_id = "ocid1.tenancy.oc1..aaaa";
    cfg.user_id = "ocid1.user.oc1..bbbb";
    cfg.fingerprint = "aa:bb:cc:dd";
    cfg.private_key_pem = pem;
    return cfg;
}

/// Verify a base64 signature over @p signing_string with @p pem's public half.
///
/// Deliberately does not share a line of code with the signer — it decodes and
/// verifies through OpenSSL directly, so a bug in the signer's own base64 or
/// digest handling shows up as a failure here rather than cancelling out.
auto verify(const std::string& pem, const std::string& signing_string, const std::string& b64_sig)
    -> bool {
    BIO* kbio = BIO_new_mem_buf(pem.data(), static_cast<int>(pem.size()));
    EVP_PKEY* key = PEM_read_bio_PrivateKey(kbio, nullptr, nullptr, nullptr);
    BIO_free_all(kbio);
    if (key == nullptr) {
        return false;
    }

    std::vector<unsigned char> sig(b64_sig.size());
    const int decoded =
        EVP_DecodeBlock(sig.data(), reinterpret_cast<const unsigned char*>(b64_sig.data()),
                        static_cast<int>(b64_sig.size()));
    std::size_t sig_len = decoded < 0 ? 0U : static_cast<std::size_t>(decoded);
    // EVP_DecodeBlock always emits a multiple of 3 bytes, over-counting by
    // however much padding the input carried.
    for (auto it = b64_sig.rbegin(); it != b64_sig.rend() && *it == '=' && sig_len > 0; ++it) {
        --sig_len;
    }

    EVP_MD_CTX* ctx = EVP_MD_CTX_new();
    EVP_DigestVerifyInit(ctx, nullptr, EVP_sha256(), nullptr, key);
    const int ok = EVP_DigestVerify(ctx, sig.data(), sig_len,
                                    reinterpret_cast<const unsigned char*>(signing_string.data()),
                                    signing_string.size());
    EVP_MD_CTX_free(ctx);
    EVP_PKEY_free(key);
    return ok == 1;
}

/// Pull the base64 signature back out of the `authorization` header, which is
/// also a small check that the header is shaped the way a server would parse it.
auto signature_of(const std::map<std::string, std::string>& headers) -> std::string {
    const std::string& auth = headers.at("authorization");
    const auto marker = std::string("signature=\"");
    const auto pos = auth.find(marker);
    BOOST_REQUIRE_MESSAGE(pos != std::string::npos, "no signature= in: " << auth);
    const auto start = pos + marker.size();
    return auth.substr(start, auth.find('"', start) - start);
}

}  // namespace

BOOST_AUTO_TEST_SUITE(oci_signing_tests)

/// The `date` header must be RFC 1123 in GMT, and must stay that way under any
/// locale. `strftime`'s `%a`/`%b` are locale-sensitive, so a build that used
/// them would emit localised day and month names on a machine whose only
/// difference is `$LC_TIME` — a failure that reproduces nowhere the author
/// looks. The expected string is written out rather than derived.
BOOST_AUTO_TEST_CASE(the_date_header_is_rfc1123_in_gmt) {
    const auto pem = generate_rsa_key_pem();
    const auto headers =
        signing::sign_request(make_config(pem), "GET", test_target, test_host, "", fixed_time);
    BOOST_CHECK_EQUAL(headers.at("date"), fixed_date);
}

/// The canonical string for a request with a body, asserted as exact bytes.
///
/// Stated as a whole-string comparison rather than a set of "contains" checks
/// because order and separators *are* the specification here — a check that
/// each header appears somewhere would pass for every wrong ordering.
BOOST_AUTO_TEST_CASE(the_canonical_string_for_a_body_request_is_the_documented_six_lines) {
    const std::string body = R"({"size":5})";
    const auto pem = generate_rsa_key_pem();
    const auto headers =
        signing::sign_request(make_config(pem), "POST", test_target, test_host, body, fixed_time);

    const std::string expected =
        std::string("date: ") + fixed_date + "\n" + "(request-target): post " + test_target + "\n" +
        "host: " + test_host + "\n" + "content-length: " + std::to_string(body.size()) + "\n" +
        "content-type: application/json\n" + "x-content-sha256: " + headers.at("x-content-sha256");

    BOOST_CHECK_EQUAL(
        signing::build_signing_string("POST", test_target, test_host, body, headers.at("date")),
        expected);
    BOOST_CHECK_MESSAGE(verify(pem, expected, signature_of(headers)),
                        "the signature does not verify over the documented canonical string");
}

/// **The control that makes the case above mean something.**
///
/// `design.md`'s first draft put `(request-target)` before `date`. If a
/// signature verified against both orderings, every other assertion in this
/// file would be vacuous. It cannot — the signature covers the bytes — and
/// this asserts that outright rather than trusting it.
BOOST_AUTO_TEST_CASE(a_signature_does_not_verify_against_the_superseded_header_order) {
    const std::string body = R"({"size":5})";
    const auto pem = generate_rsa_key_pem();
    const auto headers =
        signing::sign_request(make_config(pem), "POST", test_target, test_host, body, fixed_time);

    const std::string draft_order =
        std::string("(request-target): post ") + test_target + "\n" + "date: " + fixed_date + "\n" +
        "host: " + test_host + "\n" + "content-length: " + std::to_string(body.size()) + "\n" +
        "content-type: application/json\n" + "x-content-sha256: " + headers.at("x-content-sha256");

    BOOST_CHECK_MESSAGE(!verify(pem, draft_order, signature_of(headers)),
                        "the draft (request-target)-first order verified, so the positive case "
                        "above proves nothing about ordering");
}

/// A bodyless request signs exactly three headers and adds none of the
/// body-derived ones. Sending `content-length: 0` here would not merely be
/// redundant — it would be signed, and would not match what the service
/// reconstructs.
BOOST_AUTO_TEST_CASE(a_bodyless_request_signs_exactly_date_request_target_and_host) {
    const auto pem = generate_rsa_key_pem();
    const auto headers =
        signing::sign_request(make_config(pem), "GET", test_target, test_host, "", fixed_time);

    BOOST_CHECK(!headers.contains("content-length"));
    BOOST_CHECK(!headers.contains("content-type"));
    BOOST_CHECK(!headers.contains("x-content-sha256"));

    const std::string expected = std::string("date: ") + fixed_date + "\n" +
                                 "(request-target): get " + test_target + "\n" +
                                 "host: " + test_host;
    BOOST_CHECK_EQUAL(
        signing::build_signing_string("GET", test_target, test_host, "", headers.at("date")),
        expected);
    BOOST_CHECK_MESSAGE(verify(pem, expected, signature_of(headers)),
                        "the bodyless signature does not verify");

    const auto& auth = headers.at("authorization");
    BOOST_CHECK(auth.find(R"(headers="date (request-target) host")") != std::string::npos);
}

/// The `authorization` header's fixed fields. A server parses these, so their
/// spelling is part of the wire contract, not a formatting choice.
BOOST_AUTO_TEST_CASE(the_authorization_header_carries_the_documented_fields) {
    const std::string body = R"({"size":5})";
    const auto pem = generate_rsa_key_pem();
    const auto headers =
        signing::sign_request(make_config(pem), "POST", test_target, test_host, body, fixed_time);
    const auto& auth = headers.at("authorization");

    BOOST_CHECK(auth.starts_with(R"(Signature version="1",)"));
    BOOST_CHECK(auth.find(R"(algorithm="rsa-sha256")") != std::string::npos);
    // keyId is tenancy/user/fingerprint, in that order — a different order
    // parses fine and authenticates as nobody.
    BOOST_CHECK(auth.find(R"(keyId="ocid1.tenancy.oc1..aaaa/ocid1.user.oc1..bbbb/aa:bb:cc:dd")") !=
                std::string::npos);
    BOOST_CHECK(auth.find(R"(headers="date (request-target) host content-length content-type )"
                          R"(x-content-sha256")") != std::string::npos);
    // The signed-headers list must name exactly what the canonical string
    // contains; the count is checked so an added line cannot go unlisted.
    BOOST_CHECK_EQUAL(signing::signed_header_names(true).size(), 6U);
    BOOST_CHECK_EQUAL(signing::signed_header_names(false).size(), 3U);
}

/// Requirement 1.5: every API-key field is individually required, and the error
/// names the one that is missing. Checked field by field rather than as "an
/// incomplete config throws", because the failure this guards against is a
/// deployment with exactly one field left blank.
BOOST_AUTO_TEST_CASE(each_missing_api_key_field_is_rejected_by_name) {
    const auto pem = generate_rsa_key_pem();
    const auto base = make_config(pem);

    const auto rejects = [&](auto mutate, const std::string& field) {
        oci_client_config cfg = base;
        mutate(cfg);
        try {
            (void)signing::sign_request(cfg, "GET", test_target, test_host, "", fixed_time);
        } catch (const std::invalid_argument& e) {
            const bool names_it = std::string(e.what()).find(field) != std::string::npos;
            BOOST_CHECK_MESSAGE(names_it, "error did not name " << field << ": " << e.what());
            return true;
        } catch (...) {
            return false;
        }
        return false;
    };

    BOOST_CHECK(rejects([](auto& c) { c.tenancy_id.clear(); }, "tenancy_id"));
    BOOST_CHECK(rejects([](auto& c) { c.user_id.clear(); }, "user_id"));
    BOOST_CHECK(rejects([](auto& c) { c.fingerprint.clear(); }, "fingerprint"));
    BOOST_CHECK(rejects([](auto& c) { c.private_key_pem.clear(); }, "private_key_pem"));
}

/// Instance Principal signing is a stub, and this pins that it *fails loudly*
/// rather than silently signing with something else. Requirement 1.6 stays
/// blocked until the metadata-service contract is confirmed
/// (`spike-notes.md`, Task 0(b)); the risk being guarded against is a later
/// change that makes `use_instance_principal` quietly fall back to the API-key
/// path, which would authenticate as the wrong principal instead of erroring.
BOOST_AUTO_TEST_CASE(instance_principal_signing_fails_loudly_while_unimplemented) {
    const auto pem = generate_rsa_key_pem();
    oci_client_config cfg = make_config(pem);
    cfg.use_instance_principal = true;

    BOOST_CHECK_THROW(
        (void)signing::sign_request(cfg, "GET", test_target, test_host, "", fixed_time),
        std::runtime_error);

    bool names_the_reason = false;
    try {
        (void)signing::sign_request(cfg, "GET", test_target, test_host, "", fixed_time);
    } catch (const std::runtime_error& e) {
        names_the_reason = std::string(e.what()).find("not yet implemented") != std::string::npos;
    }
    BOOST_CHECK_MESSAGE(names_the_reason,
                        "the error should say it is unimplemented, not just fail");

    BOOST_CHECK_THROW(
        (void)signing::instance_principal_signer::sign(cfg, "GET", test_target, test_host, ""),
        std::runtime_error);
}

/// A passphrase-protected key is read with its passphrase. Worth its own case
/// because OpenSSL's default behaviour on a missing passphrase is to *prompt on
/// the terminal*, which in a server process is a hang rather than an error —
/// so "it works with an unencrypted key" says nothing about this path.
BOOST_AUTO_TEST_CASE(an_encrypted_private_key_is_read_with_its_passphrase) {
    // Re-encrypt the generated key under a passphrase.
    const auto plain_pem = generate_rsa_key_pem();
    BIO* in = BIO_new_mem_buf(plain_pem.data(), static_cast<int>(plain_pem.size()));
    EVP_PKEY* key = PEM_read_bio_PrivateKey(in, nullptr, nullptr, nullptr);
    BIO_free_all(in);
    BOOST_REQUIRE(key != nullptr);

    const std::string passphrase = "correct horse battery staple";
    BIO* out = BIO_new(BIO_s_mem());
    BOOST_REQUIRE(
        PEM_write_bio_PrivateKey(out, key, EVP_aes_256_cbc(),
                                 reinterpret_cast<const unsigned char*>(passphrase.data()),
                                 static_cast<int>(passphrase.size()), nullptr, nullptr) == 1);
    char* data = nullptr;
    const long len = BIO_get_mem_data(out, &data);  // NOLINT(google-runtime-int) — OpenSSL's type
    const std::string encrypted_pem(data, static_cast<std::size_t>(len));
    BIO_free_all(out);
    EVP_PKEY_free(key);

    BOOST_REQUIRE(encrypted_pem.find("ENCRYPTED") != std::string::npos);

    oci_client_config cfg = make_config(encrypted_pem);
    cfg.private_key_passphrase = passphrase;
    const auto headers = signing::sign_request(cfg, "GET", test_target, test_host, "", fixed_time);
    const std::string expected = std::string("date: ") + fixed_date + "\n" +
                                 "(request-target): get " + test_target + "\n" +
                                 "host: " + test_host;
    BOOST_CHECK_MESSAGE(verify(plain_pem, expected, signature_of(headers)),
                        "signing with an encrypted key produced a signature that does not verify "
                        "under the same key");

    // The wrong passphrase must fail rather than silently signing with garbage.
    oci_client_config wrong = cfg;
    wrong.private_key_passphrase = "not the passphrase";
    BOOST_CHECK_THROW(
        (void)signing::sign_request(wrong, "GET", test_target, test_host, "", fixed_time),
        std::runtime_error);
}

BOOST_AUTO_TEST_SUITE_END()
