#!/usr/bin/env python3
"""Translate a Kconfig .config/defconfig into CMake and C++ glue.

Not a fork or vendor of Kconfiglib -- a thin wrapper around its public API
(installed via `pip install -r scripts/kconfig/requirements.txt`). See
.kiro/specs/kconfig-integration/design.md for the full design.
"""
import argparse
import sys

import kconfiglib

# C++ side: preserve the *existing* macro names, not CONFIG_<NAME> -- so no
# #ifdef call site in include/, src/, tests/, or cmd/ needs to change.
# Symbols not listed here (COVERAGE, HTTP_TRANSPORT, LIBSSH2_TESTS, the
# future-backend symbols) only ever needed to reach CMake, not C++; they're
# covered by the KCONFIG_<NAME> loop below instead.
MACRO_MAP = {
    "OPENSSL": "KYTHIRA_HAS_OPENSSL",
    "HTTP_TRANSPORT_TLS": "CPPHTTPLIB_OPENSSL_SUPPORT",
    "COAP_TRANSPORT": "LIBCOAP_AVAILABLE",
    "EDHOC": "LAKERS_AVAILABLE",
    "DNS_DISCOVERY": "KYTHIRA_HAS_LDNS",
    "POCO_DISCOVERY": "KYTHIRA_HAS_POCO_DNSSD",
    "AWS_SDK": "KYTHIRA_HAS_AWS_SDK",
    "AWS_ACM_PCA": "KYTHIRA_HAS_AWS_ACM_PCA",
    "CHAOS_TESTS": "FIU_ENABLE",
}


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("kconfig_file")
    ap.add_argument("config_file", nargs="?", help="Defaults to the Kconfig-declared defaults if omitted")
    ap.add_argument("--cmake-out", required=True)
    ap.add_argument("--header-out", required=True)
    args = ap.parse_args()

    kconf = kconfiglib.Kconfig(args.kconfig_file)
    if args.config_file:
        kconf.load_config(args.config_file)
        if kconf.warnings:
            for warning in kconf.warnings:
                print(f"genconfig.py: {warning}", file=sys.stderr)
            return 1

    # CMake side: one KCONFIG_<NAME> per bool/tristate symbol, unconditionally
    # -- not every symbol needs to feed C++, but every symbol needs to be
    # visible to CMakeLists.txt so it can gate find_package()/cache-variable
    # seeding calls.
    with open(args.cmake_out, "w") as f:
        f.write("# Generated by scripts/kconfig/genconfig.py -- do not edit.\n")
        for sym in kconf.unique_defined_syms:
            if sym.type in (kconfiglib.BOOL, kconfiglib.TRISTATE):
                f.write(f"set(KCONFIG_{sym.name} {'ON' if sym.tri_value else 'OFF'})\n")

    with open(args.header_out, "w") as f:
        f.write("#pragma once\n// Generated by scripts/kconfig/genconfig.py -- do not edit.\n")
        for sym_name, macro in MACRO_MAP.items():
            sym = kconf.syms.get(sym_name)
            if sym and sym.tri_value:
                f.write(f"#define {macro} 1\n")

    return 0


if __name__ == "__main__":
    sys.exit(main())
